sailpoint-oss/sp-connector-sdk-js

lib/logger/logger.ts

Fix logger mixing merge issue, Create new object as mixin
locally with airtable connector
beforeFix
`[2022-07-26T14:19:21.723-04:00] INFO  | connectorMessage ▶︎ {"commandType":"std:account:create","invocationId":"","message":"new user account has id = chandler.bing@gmail.com\n","requestId":"0ceac279-4bc3-4fbc-9e85-fe7701033896","version":10}
[2022-07-26T14:19:21.725-04:00] INFO  | connectorMessage ▶︎ {"airtableId":"recJ06bMkzC2mU1l5","commandType":"std:account:create","connectorName":"Airtable","department":"","displayName":"","email":"chandler.bing@gmail.com","enabled":true,"entitlments":[""],"firstName":"","invocationId":"","lastName":"","locked":false,"message":"created user in …

PLTCONN-1751-fix-mergeobj-overwrite

---

bin/spcx.ts
lib/logger/logger.ts

Add option to set logger level based on config flag
Local connector testing

PLTCONN-1719: sdk - set pino logger level from connector config variable

---

package-lock.json
package.json

Update pino logger
using test connector

PLTCONN-1827-update-pino

---

bin/spcx.ts

Fix file watching and -S problem on windows
Manually tested in windows, linux and macOS

PLTCONN-2270: Fix file watching and -S problem on windows

---

bin/spcx.ts
package-lock.json
package.json

- Add packaging command into sdk
- Most of the changes from this github view is just wrapping existing code into a function. There is no changes to existing npm run dev code
Tested locally in mac and windows

PLTCONN-1774: Add packaging command into sdk

---

lib/commands/std-change-password.ts

PLTCONN-2597: Refactor change password input

---

.github/workflows/release.yml
package-lock.json
package.json

Add allow same version flag
Tested in forked repo and local

PLTCONN-1789: Add allow same version flag

---

README.md
lib/connector.ts
package-lock.json
package.json

PLTCONN-2760: Remove beta and mark version 1.0.0

---

lib/commands/command.ts
lib/commands/std-account-list.ts
lib/commands/std-entitlement-list.ts
lib/connector.spec.ts
lib/handler.ts
lib/response/index.ts

Supports stateful command for account and entitlement list
Unit tests

PLTCONN-2322: Supports stateful command

---

lib/commands/std-source-data-discover.ts
lib/commands/std-source-data-read.ts

Tested using new connector
Unit tests
Test run

PLTFORMS-1855: Changing output to array

---

lib/connector-spec.ts

Also attempt to read `connector-spec.json` from directory where connector code is running.

PLTCONN-3953: fix connector spec read

---

lib/commands/std-account-list.ts
lib/commands/std-account-read.ts

Support direct permissions for accounts

PLTCONN-4010: [sdk] Support direct permissions for accounts

---

lib/commands/command.ts
lib/commands/std-account-create.ts
lib/commands/std-account-update.ts

Update SDK to allow the new result field
Tested manually by applying to sample connector and run in IDN

PLTCONN-4024: Update SDK to allow the new result field

---

lib/commands/std-account-list.ts

PLTCONN-3736: Add incomplete and final update flags to the account list response

---

lib/commands/std-test-connection.ts
lib/connector-handler.ts

Pass account schema into test connection command
Manually tested

PLTCONN-4499: Pass account schema into test connection command

---

package-lock.json
package.json

PLTCONN-4973: update express package

---

lib/connector-customizer.spec.ts
lib/connector-handler.ts
lib/connector.spec.ts

PLTCONN-5210 external role response

---

package-lock.json
package.json

This PR updates archiver and jest to versions that no longer require the inflight dependency.
Unit and integration testing.

PLTCONN-5916: Update archiver and jest to attempt to remove dependency on inflight

---

package-lock.json
package.json

debug dependencies of express.js need to be updated to eliminate vulnerabilities.
Unit and integration testing.

PLTCONN-5917: Override debug version

---

lib/logger/logger.ts

We've added additional fields to context over time. Only some of them are ones that we actually want to log.

PLTCONN-6451: Only log fields from context we are interested in

---

lib/commands/std-application-discovery-list.ts

- JIRA: https://sailpoint.atlassian.net/browse/CONJUBILEE-3123
- Fix for Output Schema validation error for application discovery command
- Tested mannually

CONJUBILEE-3123: Updating CommandOutput with valid command output schema

---

lib/filter.spec.ts
lib/filter.ts
package-lock.json
package.json

> Aggregation-filtering-enhacements
> Have unit tests and have tested it locally by providing different type of complex and simple filters

Aggregation-filtering-enhacements

---

package-lock.json
package.json

https://github.com/debug-js/debug/commits/master/src/common.js

PLTCONN-5609: Fixing vulnerability problem
